version: "3.9"

services:
  minio: # https://hub.docker.com/r/bitnami/minio
    image: bitnami/minio:2024.5.28-debian-12-r0
    network_mode: host
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${CACHE_DIR:-./cache}/volumes/minio/data:/bitnami/minio/data
    user: "0:0"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
